let Q=null;
function qGroup(t){return typeof group==='function'?group(t):'ALL'}
function qShuffle(a){let b=[...a];for(let i=b.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function qEnglish(t){return ENGLISH[String(t['正式/標準用語']||'')]||null}
function qPool(mode,genre){return DATA.filter(t=>(genre==='ALL'||qGroup(t)===genre)&&(mode!=='sentence'||qEnglish(t)?.[0]))}
function openQuiz(){if(!Learning.ready){alert('保存機能を準備中です。少し待ってください。');return}if(!Learning.finishQuiz(Q))return;Q=null;MotionDiagram.stop();document.getElementById('app').style.display='none';let a=document.getElementById('quizArea');a.style.display='block';document.getElementById('quiz').innerHTML='<div class="quizsetup"><div class="eyebrow">ZERO ONE QUIZ</div><h2>バスケと言葉を、実戦につなげる。</h2><div class="quizgrid"><label>出題<select id="qm" class="quizselect"><option value="spell">SPELL｜英単語 → 意味</option><option value="listen">LISTEN｜聞く → 意味</option><option value="meaning">MEANING｜意味 → 英単語</option><option value="sentence">COACH ENGLISH｜意味 → 実戦英文</option></select></label><label>回答<select id="qa" class="quizselect"><option value="choice">5択</option><option value="free">自由記入</option></select></label><label>問題数<select id="qn" class="quizselect"><option>5</option><option>10</option><option>30</option></select></label><label>ジャンル<select id="qg" class="quizselect"><option value="ALL">ALL</option><option>OFFENSE</option><option>DEFENSE</option><option>SKILL</option><option>COURT</option><option>RULE</option></select></label></div><button class="quizgo" onclick="startQuiz()">START QUIZ</button><button class="qback" onclick="closeQuiz()">辞書へ戻る</button></div>'}
function closeQuiz(){if(!Learning.finishQuiz(Q))return;Q=null;document.getElementById('quizArea').style.display='none';document.getElementById('app').style.display=''}
function startQuiz(){let mode=document.getElementById('qm').value,answer=document.getElementById('qa').value,n=+document.getElementById('qn').value,genre=document.getElementById('qg').value,pool=qPool(mode,genre);if(pool.length<n){alert('この条件では'+pool.length+'問です。問題数かジャンルを変更してください。');return}Q={mode,answer,genre,items:qShuffle(pool).slice(0,n),i:0,score:0,locked:false};Learning.beginQuiz(Q);showQuizQuestion()}
function qCorrect(t){if(Q.mode==='spell'||Q.mode==='listen')return String(t['日本語推奨表記']||'');if(Q.mode==='meaning')return String(t['正式/標準用語']||'');return qEnglish(t)?.[0]||''}
function qStem(t){if(Q.mode==='spell')return '<div class="qprompt">'+esc(t['正式/標準用語'])+'</div>';if(Q.mode==='listen')return '<div class="qprompt">LISTENを押して英語を聞き、意味を答えてください。</div><button class="qlisten" onclick="speak(\''+esc(t['正式/標準用語']).replace(/'/g,"\\'")+'\')">▶ LISTEN</button>';if(Q.mode==='meaning')return '<div class="qprompt">'+esc(t['定義'])+'</div>';return '<div class="qprompt">'+esc(qEnglish(t)?.[1]||'')+'</div>'}
function showQuizQuestion(){let t=Q.items[Q.i],body='';Q.options=[];Q.selectedId=null;if(Q.answer==='choice'){let others=qShuffle(qPool(Q.mode,Q.genre).filter(x=>x.ID!==t.ID&&qCorrect(x)!==qCorrect(t))).slice(0,4);let opts=qShuffle([t,...others]);Q.options=opts;body='<div class="choices">'+opts.map(x=>'<button class="choice" onclick="quizChoice(\''+esc(x.ID)+'\')">'+esc(qCorrect(x))+'</button>').join('')+'</div>'}else{body='<input id="qfree" class="answerinput" autocomplete="off" placeholder="回答を入力"><button class="quizgo" onclick="quizFree()">回答する</button>'}document.getElementById('quiz').innerHTML='<div class="quizcard"><button class="qback" onclick="closeQuiz()">← 辞書</button><div class="qprogress">QUESTION '+(Q.i+1)+' / '+Q.items.length+'　SCORE '+Q.score+'</div>'+qStem(t)+body+'<div id="qfeedback"></div></div>'}
function qNorm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9ぁ-んァ-ヶ一-龠]/g,'')}
function quizChoice(id){if(Q.locked)return;Q.selectedId=id;finishQuizAnswer(id===Q.items[Q.i].ID)}
function quizFree(){if(Q.locked)return;let t=Q.items[Q.i],v=qNorm(document.getElementById('qfree').value),answers=[];if(Q.mode==='spell'||Q.mode==='listen')answers=[t['日本語推奨表記'],t['別称']];else if(Q.mode==='meaning')answers=[t['正式/標準用語'],t['別称'],t['略語']];else answers=[qEnglish(t)?.[0]];finishQuizAnswer(answers.filter(Boolean).some(x=>qNorm(x)===v))}
function finishQuizAnswer(ok){if(!Q||Q.locked)return;Q.locked=true;Learning.answerQuiz(Q,Q.items[Q.i].ID,ok);if(ok)Q.score++;let t=Q.items[Q.i],e=qEnglish(t),extra=Q.mode==='sentence'&&e?.[2]?'<br><small>PLAYER CALL: '+esc(e[2])+'</small>':'';document.querySelectorAll('.choice,.quizgo,.answerinput').forEach(x=>x.disabled=true);document.getElementById('qfeedback').innerHTML='<div class="feedback '+(ok?'good':'bad')+'"><b>'+(ok?'GOOD!':'ANSWER')+'</b><br>'+esc(qCorrect(t))+extra+'</div>'+qAnswerReview(t)+'<button class="qnext" onclick="nextQuizQuestion()">'+(Q.i+1===Q.items.length?'RESULT':'NEXT →')+'</button>'}
function nextQuizQuestion(){Q.i++;Q.locked=false;if(Q.i>=Q.items.length){document.getElementById('quiz').innerHTML='<div class="quizresult"><div class="eyebrow">QUIZ COMPLETE</div><h2>'+Q.score+' / '+Q.items.length+'</h2><p>正答率 '+Math.round(Q.score/Q.items.length*100)+'%</p><button class="quizgo" onclick="openQuiz()">もう一度</button><button class="qback" onclick="closeQuiz()">辞書へ戻る</button></div>';return}showQuizQuestion()}
function qAnswerReview(correct){
 const options=Q.answer==='choice'?Q.options:[correct];
 return '<section class="answer-review"><h3>'+(Q.answer==='choice'?'選択肢すべての意味':'用語の意味')+'</h3>'+options.map(t=>{
  const right=t.ID===correct.ID,chosen=t.ID===Q.selectedId,e=qEnglish(t);
  return '<article class="answer-review-item'+(right?' is-correct':'')+'"><div class="answer-review-label">'+(right?'<span>正解</span>':'')+(chosen?'<span>あなたの回答</span>':'')+'</div><b>'+esc(t['正式/標準用語'])+'</b><div class="answer-review-jp">'+esc(t['日本語推奨表記']||'')+'</div><p>'+esc(t['定義']||'意味は準備中です。')+'</p>'+(Q.mode==='sentence'&&e?'<div class="answer-review-example"><b>'+esc(e[0])+'</b><br>'+esc(e[1]||'')+'</div>':'')+'</article>';
 }).join('')+'</section>';
}
