const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const http=require('node:http');
const {createHash}=require('node:crypto');
const {chromium,webkit}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(process.env.UPDATE_ROOT||'.');
const native=JSON.parse(fs.readFileSync(path.join(root,'app-version.json')));
const app=native.app,slug={CANVAS:'basketball-tactics-board',PRACTICE:'zero-one-practice-lab',ROSTER:'zero-one-roster',TERMINOLOGY:'zero-one-terminology'}[app];
const swPath={CANVAS:'service-worker.js',PRACTICE:'sw.js'}[app]||'';
const hash=value=>createHash('sha256').update(value).digest('hex');
const controller=fs.readFileSync(path.join(root,'zero-one-update.js'),'utf8'),css=fs.readFileSync(path.join(root,'zero-one-update.css'),'utf8');
const workerSource=swPath?fs.readFileSync(path.join(root,swPath),'utf8'):'';
function release(label){const id=hash(label+controller+workerSource),script=`window.fixtureLoaded=${JSON.stringify(label)};window.fixtureProtection={ready:true,dirty:false,busy:false};window.ZeroOneUpdateGuard=()=>window.fixtureProtection;`;
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="zero-one-build" content="${id}" data-app="${app}" data-worker="${swPath}" data-version-mount="#about"><link rel="stylesheet" href="zero-one-update.css?build=${id}"></head><body><main><h1>${label}</h1><input id="draft" value="saved"><div id="about"></div></main><script src="fixture-app.js?build=${id}"></script><script src="zero-one-update.js?build=${id}"></script></body></html>`;
const files={'index.html':html,'fixture-app.js':script,'zero-one-update.js':controller,'zero-one-update.css':css};const manifest={schema:1,app,buildId:id,files:Object.entries(files).map(([path,body])=>({path,sha256:hash(body)}))};
return {id,files,manifest,worker:workerSource.replace(/const BUILD_ID='[a-f0-9]{64}';/,`const BUILD_ID='${id}';`)};}
const versions=[release('A'),release('B')],results=[];
async function record(engine,name,fn){await fn();results.push({engine,name,pass:true});console.log('PASS',engine,app,name);}
const msal=`window.msal={PublicClientApplication:class{async initialize(){}async handleRedirectPromise(){return null}getAllAccounts(){return []}getActiveAccount(){return null}setActiveAccount(){}async acquireTokenSilent(){throw Error('No test account')} }};`;
(async()=>{
for(const [engine,type] of Object.entries({chromium,webkit})){
 let originOnline=true,stage=0,failVersion=false,delayVersion=false,corrupt=false,nativeMode=false,versionRequests=0;
 const server=http.createServer((req,res)=>{if(!originOnline){req.socket.destroy();return;}const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith('/'+slug+'/'))return res.writeHead(404).end();const name=url.pathname.slice(slug.length+2)||'index.html';res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',name.endsWith('.js')||name.endsWith('.mjs')?'text/javascript':name.endsWith('.json')?'application/json':name.endsWith('.css')?'text/css':name.endsWith('.wasm')?'application/wasm':name.endsWith('.png')?'image/png':'text/html');
  if(nativeMode){try{return res.end(fs.readFileSync(path.join(root,name)));}catch{return res.writeHead(404).end();}}
  const version=versions[stage];if(name==='app-version.json'){versionRequests++;if(failVersion)return res.writeHead(503).end('interrupted');if(delayVersion)return setTimeout(()=>res.end(JSON.stringify(version.manifest)),250);return res.end(JSON.stringify(version.manifest));}if(name===swPath)return res.end(version.worker);if(corrupt&&name==='fixture-app.js')return res.end('window.fixtureLoaded="partial";');if(version.files[name]!==undefined)return res.end(version.files[name]);res.writeHead(404).end();
 });await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const base=`http://127.0.0.1:${server.address().port}/${slug}/`,profile=fs.mkdtempSync(path.join(os.tmpdir(),'safe-update-'+app+'-'));
 const context=await type.launchPersistentContext(path.join(profile,'profile'),{headless:true,viewport:{width:390,height:844},env:{...process.env,HOME:profile,CFFIXED_USER_HOME:profile,XDG_DATA_HOME:path.join(profile,'data'),XDG_CACHE_HOME:path.join(profile,'cache'),XDG_CONFIG_HOME:path.join(profile,'config')}});
 try{
 if(engine==='webkit')await context.addInitScript(()=>Object.defineProperty(navigator,'standalone',{value:true,configurable:true}));
 const page=await context.newPage();await page.goto(base+'?filter=keep#section');await page.waitForFunction(()=>window.zeroOneUpdater);if(swPath)await page.waitForFunction(()=>navigator.serviceWorker.controller);
 await record(engine,'first installation has no update notice',async()=>{await page.evaluate(()=>zeroOneUpdater.check(true));assert.equal(await page.locator('#zeroOneUpdateNotice:visible').count(),0);assert.equal(await page.evaluate(()=>fixtureLoaded),'A');});
 await page.evaluate(async()=>{localStorage.setItem('msal.synthetic.account','signed-in-sentinel');localStorage.setItem('user.plan','{"name":"saved","version":1}');sessionStorage.setItem('msal.synthetic.session','session-sentinel');await(await caches.open('other-app-owned')).put('./other-app',new Response('keep'));await new Promise((resolve,reject)=>{const request=indexedDB.open('update-data',1);request.onupgradeneeded=()=>request.result.createObjectStore('records');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction('records','readwrite');tx.objectStore('records').put({id:'saved',content:[1,2,3]},'plan');tx.oncomplete=()=>{db.close();resolve();};};});});
 await page.locator('#draft').fill('unsaved draft');const retained=await context.newPage();await retained.goto(base);await retained.waitForFunction(()=>window.zeroOneUpdater);await retained.locator('#draft').fill('retained draft');
 stage=1;await page.evaluate(()=>zeroOneUpdater.check(true));
 await record(engine,'actual published build prompts once without reloading',async()=>{await page.locator('#zeroOneUpdateNotice').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>fixtureLoaded),'A');assert.equal(await page.locator('#draft').inputValue(),'unsaved draft');const before=versionRequests;await page.evaluate(()=>{window.dispatchEvent(new Event('pageshow'));window.dispatchEvent(new Event('focus'));document.dispatchEvent(new Event('visibilitychange'));});assert(versionRequests-before<=1);assert.equal(await page.locator('#zeroOneUpdateNotice').count(),1);assert.match(await page.locator('#zeroOneUpdateMessage').textContent(),/新しいバージョンがあります/);});
 await page.evaluate(()=>fixtureProtection.dirty=true);await page.locator('#zeroOneUpdateNotice button').click();await record(engine,'unsaved work blocks explicit update',async()=>{assert.match(await page.locator('#zeroOneUpdateMessage').textContent(),/保存/);assert.equal(await page.evaluate(()=>fixtureLoaded),'A');});
 await page.evaluate(()=>{fixtureProtection.dirty=false;fixtureProtection.busy=true;});await page.locator('#zeroOneUpdateNotice button').click();await record(engine,'save and sync in progress block update',async()=>{assert.match(await page.locator('#zeroOneUpdateMessage').textContent(),/完了/);assert.equal(await page.evaluate(()=>fixtureLoaded),'A');});await page.evaluate(()=>fixtureProtection.busy=false);
 await context.setOffline(true);await record(engine,'offline preserves current app and disables update',async()=>{await page.waitForFunction(()=>!navigator.onLine&&document.querySelector('#zeroOneUpdateNotice button').disabled);assert.equal(await page.locator('#zeroOneUpdateNotice button').isDisabled(),true);assert.equal(await page.evaluate(()=>fixtureLoaded),'A');});await context.setOffline(false);await page.waitForFunction(()=>navigator.onLine);await page.waitForFunction(()=>!document.querySelector('#zeroOneUpdateNotice button').disabled);
 failVersion=true;await page.locator('#zeroOneUpdateNotice button').click();await record(engine,'interrupted version request leaves current data/code usable',async()=>{await page.waitForFunction(()=>!document.querySelector('#zeroOneUpdateNotice button').disabled);assert.equal(await page.evaluate(()=>fixtureLoaded),'A');assert.equal(await page.locator('#draft').inputValue(),'unsaved draft');});failVersion=false;
 if(!swPath){corrupt=true;await page.locator('#zeroOneUpdateNotice button').click();await record(engine,'partial assets never trigger reload',async()=>{await page.waitForFunction(()=>document.getElementById('zeroOneUpdateMessage').textContent.includes('配信の完了'));assert.equal(await page.evaluate(()=>fixtureLoaded),'A');});corrupt=false;}
 delayVersion=true;await page.locator('#zeroOneUpdateNotice button').click();await page.evaluate(()=>fixtureProtection.dirty=true);await record(engine,'editing during preparation cancels final activation',async()=>{await page.waitForFunction(()=>!document.querySelector('#zeroOneUpdateNotice button').disabled);assert.match(await page.locator('#zeroOneUpdateMessage').textContent(),/保存/);assert.equal(await page.evaluate(()=>fixtureLoaded),'A');});delayVersion=false;await page.evaluate(()=>fixtureProtection.dirty=false);
 await page.locator('#zeroOneUpdateNotice button').click();await page.waitForURL(url=>url.searchParams.get('zeroOneBuild')===versions[1].id);await page.waitForFunction(()=>fixtureLoaded==='B'&&window.zeroOneUpdater);
 await record(engine,'explicit update loads deployed B and preserves URL/auth/storage',async()=>{const url=new URL(page.url());assert.equal(url.pathname,'/'+slug+'/');assert.equal(url.searchParams.get('filter'),'keep');assert.equal(url.hash,'#section');const actual=await page.evaluate(async()=>({account:localStorage.getItem('msal.synthetic.account'),plan:localStorage.getItem('user.plan'),session:sessionStorage.getItem('msal.synthetic.session'),cache:await(await(await caches.open('other-app-owned')).match('./other-app')).text(),record:await new Promise(resolve=>{const r=indexedDB.open('update-data');r.onsuccess=()=>{const db=r.result,q=db.transaction('records').objectStore('records').get('plan');q.onsuccess=()=>{db.close();resolve(q.result);};};})}));assert.deepEqual(actual,{account:'signed-in-sentinel',plan:'{"name":"saved","version":1}',session:'session-sentinel',cache:'keep',record:{id:'saved',content:[1,2,3]}});});
 await record(engine,'another tab never auto-reloads or loses its draft',async()=>{assert.equal(await retained.evaluate(()=>fixtureLoaded),'A');assert.equal(await retained.locator('#draft').inputValue(),'retained draft');if(swPath){await retained.waitForFunction(()=>navigator.serviceWorker.controller);const text=await retained.evaluate(()=>fetch('./fixture-app.js').then(r=>r.text()));assert.match(text,/fixtureLoaded="A"/);}});
 await page.evaluate(()=>zeroOneUpdater.check(true));await record(engine,'foreground of unchanged version has no false notice',async()=>assert.equal(await page.locator('#zeroOneUpdateNotice:visible').count(),0));
 if(swPath){originOnline=false;await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>fixtureLoaded==='B');await record(engine,'new version still opens offline',async()=>{assert.equal(await page.evaluate(()=>localStorage.getItem('user.plan')),'{"name":"saved","version":1}');assert.equal(await page.locator('#zeroOneUpdateNotice:visible').count(),0);});originOnline=true;}
 const authUrl=base+'?code=synthetic&state=synthetic#access_token=synthetic';await page.goto(authUrl);await page.waitForFunction(()=>window.zeroOneUpdater);await record(engine,'OAuth callbacks never redirect or prompt',async()=>{assert.equal(page.url(),authUrl);assert.equal(await page.locator('#zeroOneUpdateNotice:visible').count(),0);});
 await context.close();
 // Real application: separate browser profile, native guard and existing save boot.
 nativeMode=true;const nativeProfile=fs.mkdtempSync(path.join(os.tmpdir(),'safe-update-native-'+app+'-'));const real=await type.launchPersistentContext(path.join(nativeProfile,'profile'),{headless:true,viewport:{width:390,height:844},env:{...process.env,HOME:nativeProfile,CFFIXED_USER_HOME:nativeProfile,XDG_DATA_HOME:path.join(nativeProfile,'data'),XDG_CACHE_HOME:path.join(nativeProfile,'cache'),XDG_CONFIG_HOME:path.join(nativeProfile,'config')}});
 try{await real.route('**/*msal-browser.min.js*',route=>route.fulfill({contentType:'text/javascript',body:msal}));const actual=await real.newPage(),faults=[];actual.on('pageerror',error=>faults.push(error.message));await actual.goto(base);await actual.waitForFunction(()=>window.ZeroOneUpdateGuard?.().ready===true).catch(async error=>{console.error('Native boot details',JSON.stringify({faults,notice:await actual.locator('#notice').textContent().catch(()=>null),guard:await actual.evaluate(()=>window.ZeroOneUpdateGuard?.()).catch(e=>e.message)}));throw error;});await record(engine,'actual app boots with its native update guard',async()=>{assert.equal(await actual.locator('meta[name="zero-one-build"]').getAttribute('content'),native.buildId);assert.equal(faults.length,0,faults.join('\n'));});
 if(app==='PRACTICE'){await actual.locator('#title').fill('protected practice');await record(engine,'native practice draft is protected',async()=>assert.equal(await actual.evaluate(()=>ZeroOneUpdateGuard().dirty),true));}
 else if(app==='ROSTER'){await actual.evaluate(()=>openPlayer());await actual.locator('#lastName').fill('protected player');await record(engine,'native roster form is protected',async()=>assert.equal(await actual.evaluate(()=>ZeroOneUpdateGuard().dirty),true));}
 else if(app==='TERMINOLOGY'){await actual.evaluate(()=>{openQuiz();startQuiz();});await record(engine,'native unfinished quiz is protected',async()=>assert.equal(await actual.evaluate(()=>ZeroOneUpdateGuard().dirty),true));}
 else{await actual.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());openAppSettings();});await record(engine,'native canvas input dialog is protected',async()=>assert.equal(await actual.evaluate(()=>ZeroOneUpdateGuard().dirty),true));}
 }finally{await real.close();}
 }finally{await context.close().catch(()=>{});server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
}
fs.mkdirSync('reports/safe-update',{recursive:true});fs.writeFileSync('reports/safe-update/results.json',JSON.stringify({app,results,passed:true,realMicrosoft:false,physicalIPhone:false},null,2));
})().catch(error=>{console.error(error);fs.mkdirSync('reports/safe-update',{recursive:true});fs.writeFileSync('reports/safe-update/results.json',JSON.stringify({app,results,passed:false,error:error.stack},null,2));process.exitCode=1;});
